"""
Bare (company-suffix-free) standard group ID prefixes (Phase 7C) - a Python mirror of Android's
`StandardSystemGroups` constants (`domain/accounting/PrimaryGroup.kt`). The full ID for a given
company is always `f"{THIS}_{company_id}"`, exactly matching the Kotlin convention. Centralized
here so P&L/Balance Sheet classification can check exact groupId ancestry via
`domain/reports/group_aggregation.py`, never a name/string match.
"""
from __future__ import annotations

CAPITAL_GROUP_ID = "GRP_CAPITAL"
RESERVES_GROUP_ID = "GRP_RESERVES"
CURRENT_ASSETS_GROUP_ID = "GRP_CURRENT_ASSETS"
BANK_GROUP_ID = "GRP_BANK"
CASH_GROUP_ID = "GRP_CASH"
DEPOSITS_GROUP_ID = "GRP_DEPOSITS"
LOANS_ADVANCES_GROUP_ID = "GRP_LOANS_ADV"
STOCK_GROUP_ID = "GRP_STOCK"
DEBTORS_GROUP_ID = "GRP_DEBTORS"
FIXED_ASSETS_GROUP_ID = "GRP_FIXED_ASSETS"
INVESTMENTS_GROUP_ID = "GRP_INVESTMENTS"
MISC_EXPENSES_GROUP_ID = "GRP_MISC_EXP"
CURRENT_LIABILITIES_GROUP_ID = "GRP_CURRENT_LIAB"
DUTIES_GROUP_ID = "GRP_DUTIES"
PROVISIONS_GROUP_ID = "GRP_PROVISIONS"
CREDITORS_GROUP_ID = "GRP_CREDITORS"
LOANS_GROUP_ID = "GRP_LOANS"
BANK_OD_GROUP_ID = "GRP_BANK_OD"
SECURED_LOANS_GROUP_ID = "GRP_SECURED_LOANS"
UNSECURED_LOANS_GROUP_ID = "GRP_UNSECURED_LOANS"
BRANCH_DIVISIONS_GROUP_ID = "GRP_BRANCH_DIV"
SALES_GROUP_ID = "GRP_SALES"
DIRECT_INCOME_GROUP_ID = "GRP_DIR_INCOME"
INDIRECT_INCOME_GROUP_ID = "GRP_INDIR_INCOME"
PURCHASE_GROUP_ID = "GRP_PURCHASE"
DIRECT_EXPENSE_GROUP_ID = "GRP_DIR_EXP"
INDIRECT_EXPENSE_GROUP_ID = "GRP_INDIR_EXP"
SUSPENSE_GROUP_ID = "GRP_SYS_SUSPENSE"
ROUND_OFF_GROUP_ID = "GRP_SYS_ROUND_OFF"
